### ISSUE TITLE
Error when trying to run pytripgui

### ISSUE THREAD

**Issue by TokePrintz** [pytrip/pytripgui#181]
On a laptop with 64-bit ubuntu 14.04 and python 2.7.6, I followed this guide:

https://pypi.org/project/pytrip98gui/

To succesfully install pytrip98gui (and the dependencies listed in the guide).

Now however, I get

```
trip@han:~$ pytripgui 
Traceback (most recent call last): 
  File "/usr/local/bin/pytripgui", line 7, in <module> 
    from pytripgui.main import start 
  File "/usr/local/lib/python2.7/dist-packages/pytripgui/__init__.py", line 18, in <module> 
    from pytripgui.main import start, MainFrame 
  File "/usr/local/lib/python2.7/dist-packages/pytripgui/main.py", line 30, in <module> 
    from pytripgui.leftmenu import LeftMenuTree 
  File "/usr/local/lib/python2.7/dist-packages/pytripgui/leftmenu.py", line 21, in <module> 
    from pytripgui.data import TripPlan, Field 
  File "/usr/local/lib/python2.7/dist-packages/pytripgui/data.py", line 29, in <module> 
    from pytrip.ctimage import CTImages 
ImportError: No module named ctimage 
```

But I cannot find the _data.py_ file let alone the from _pytrip.ctimage import CTImages_ line, nor the ctimage module, so I have insofar been unable to figure out the issue.

**Comment by grzanka** [comment]
Python 2.7.6 was released 2013-11-10, can't you update to a bit modern version ?

**Comment by TokePrintz** [comment]
Okay, now I updated to 2.7.14. Apparently, ubuntu 14 no longer updated python to newest version just with the simple "apt-get install python". I know 2.7.14 is also not the very newest, but it should do? 

Now however, I get this 

```
trip@han:~$ pytripgui
Traceback (most recent call last):
  File "/usr/local/bin/pytripgui", line 7, in <module>
    from pytripgui.main import start
  File "/usr/local/lib/python2.7/dist-packages/pytripgui/__init__.py", line 18, in <module>
    from pytripgui.main import start, MainFrame
  File "/usr/local/lib/python2.7/dist-packages/pytripgui/main.py", line 28, in <module>
    from pytrip.error import InputError
  File "/usr/local/lib/python2.7/dist-packages/pytrip/__init__.py", line 27, in <module>
    from pytrip.cube import Cube
  File "/usr/local/lib/python2.7/dist-packages/pytrip/cube.py", line 29, in <module>
    import numpy as np
  File "/usr/local/lib/python2.7/dist-packages/numpy/__init__.py", line 160, in <module>
    from . import random
  File "/usr/local/lib/python2.7/dist-packages/numpy/random/__init__.py", line 99, in <module>
    from .mtrand import *
ImportError: /usr/local/lib/python2.7/dist-packages/numpy/random/mtrand.so: undefined symbol: PyFPE_jbuf
```

**Comment by grzanka** [comment]
Again - it looks like enviroment issue on your side. Maybe installing Conda (Anaconda / Miniconda) could help. Then you could get really newest stuff

**Comment by TokePrintz** [comment]
On 64bit ubuntu 18.04 with python 2.7.15, I still get the error I started with:

```
Traceback (most recent call last):
  File "/usr/local/bin/pytripgui", line 7, in <module>
    from pytripgui.main import start
  File "/usr/local/lib/python2.7/dist-packages/pytripgui/__init__.py", line 18, in <module>
    from pytripgui.main import start, MainFrame
  File "/usr/local/lib/python2.7/dist-packages/pytripgui/main.py", line 30, in <module>
    from pytripgui.leftmenu import LeftMenuTree
  File "/usr/local/lib/python2.7/dist-packages/pytripgui/leftmenu.py", line 21, in <module>
    from pytripgui.data import TripPlan, Field
  File "/usr/local/lib/python2.7/dist-packages/pytripgui/data.py", line 29, in <module>
    from pytrip.ctimage import CTImages
ImportError: No module named ctimage
```
Python 2.7.15 was released May 2015 an Ubuntu 18.04 is equally new. I fail to see how Conda can provide anything much newer than that?

**Comment by nbassler** [comment]
This sounds like a very old version of pytripgui you try to run. CTImages was ditched long time ago.

Use the most recent version from the master branch. That is compatible with recent pytrip version. (@grzanka think we better release this soon, even if much functionality will die)

**Comment by TokePrintz** [comment]
Well, I just used the guide given here on the site ;-P

Stupid question: To install the version from master branch, do I then have to extract the code from github and compile myself?

**Comment by grzanka** [comment]
Try installing via pip from github:
`pip install git+https://github.com/pytrip/pytripgui`
or a specific branch:
`pip install git+https://github.com/pytrip/pytripgui@BRANCHNAME`

Try googling this method as I could made a mistake...

**Comment by nbassler** [comment]
otherwise:
`git clone git@github.com:pytrip/pytripgui.git` if you start from fresh

or if you already have it checked out, switch to the master branch:
`git checkout master`
and make sure it is up to date
`git pull`

start the GUI with
`PYTHONPATH=. python3 pytripgui/main.py`
