### ISSUE TITLE
config file incompatible between python3 and 2

### ISSUE THREAD

**Issue by nbassler** [pytrip/pytripgui#191]
pickled python3 data cannot be read in python2, throwing an error.

```
bassler@baslup:~/Projects/pytripgui$ PYTHONPATH=. python pytripgui/main.py 
Traceback (most recent call last):
  File "pytripgui/main.py", line 79, in <module>
    sys.exit(main(sys.argv[1:]))
  File "pytripgui/main.py", line 71, in main
    w = AppWindow()
  File "pytripgui/main.py", line 28, in __init__
    self.ctrl = MainController(self)
  File "/home/bassler/Projects/pytripgui/pytripgui/controller/main_cont.py", line 32, in __init__
    self._open_settings()  # open settings file and update model
  File "/home/bassler/Projects/pytripgui/pytripgui/controller/main_cont.py", line 41, in _open_settings
    self.settings = SettingsController(model)
  File "/home/bassler/Projects/pytripgui/pytripgui/controller/settings_cont.py", line 33, in __init__
    self.load()
  File "/home/bassler/Projects/pytripgui/pytripgui/controller/settings_cont.py", line 48, in load
    _ms = pickle.load(f)
  File "/usr/lib/python2.7/pickle.py", line 1384, in load
    return Unpickler(file).load()
  File "/usr/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 892, in load_proto
    raise ValueError, "unsupported pickle protocol: %d" % proto
ValueError: unsupported pickle protocol: 3
```

**Comment by nbassler** [comment]
From https://docs.python.org/3/library/pickle.html

> Protocol version 0 is the original “human-readable” protocol and is backwards compatible with earlier versions of Python.

> Protocol version 1 is an old binary format which is also compatible with earlier versions of Python.
>
> Protocol version 2 was introduced in Python 2.3. It provides much more efficient pickling of new-style classes. Refer to PEP 307 for information about improvements brought by protocol 2.
>
> Protocol version 3 was added in Python 3.0. It has explicit support for bytes objects and cannot be unpickled by Python 2.x. This is the default protocol, and the recommended protocol when compatibility with other Python 3 versions is required.
>
>Protocol version 4 was added in Python 3.4. It adds support for very large objects, pickling more kinds of objects, and some data format optimizations. Refer to PEP 3154 for information about improvements brought by protocol 4.

Suggest to to use protocol 2, so both python versions will work.
```
pickle.dump(obj, file, protocol=2, fix_imports=True)
```

**Comment by grzanka** [comment]
This won't be fixed, we support only Python 3
