### ISSUE TITLE
pytripgui doesn't start

### ISSUE THREAD

**Issue by nbassler** [pytrip/pytripgui#192]
fresh debian testing install (10.0 Buster, RC1).

PyTRiP98GUI 0.3.2.post.dev15 using PyTRiP98 2.5.4

```
$ python3 --version
Python 3.7.3rc1

$ PYTHONPATH=. python3 pytripgui/main.py 
Traceback (most recent call last):
  File "pytripgui/main.py", line 79, in <module>
    sys.exit(main(sys.argv[1:]))
  File "pytripgui/main.py", line 72, in main
    w.open_files(parsed_args)
  File "pytripgui/main.py", line 33, in open_files
    if args.ctx:
AttributeError: 'NoneType' object has no attribute 'ctx'
```

**Comment by nbassler** [comment]
ok, turned out to be an old main.py file. It is ok.
However, will suggest a small change for future robustness.
