### ISSUE TITLE
Can't install from pip

### ISSUE THREAD

**Issue by nbassler** [pytrip/pytripgui#20]
```
root@baslup:/home/bassler# pip --version
pip 8.1.2 from /usr/lib/python2.7/dist-packages (python 2.7)
```

well then:

```
root@baslup:/home/bassler# pip install --upgrade pytrip98
Requirement already up-to-date: pytrip98 in /usr/local/lib/python2.7/dist-packages
Collecting numpy (from pytrip98)
  Downloading numpy-1.11.1-cp27-cp27mu-manylinux1_x86_64.whl (15.3MB)
    100% |████████████████████████████████| 15.3MB 115kB/s 
Collecting scipy (from pytrip98)
  Downloading scipy-0.18.1-cp27-cp27mu-manylinux1_x86_64.whl (40.3MB)
    100% |████████████████████████████████| 40.3MB 44kB/s 
Requirement already up-to-date: matplotlib in /usr/local/lib/python2.7/dist-packages (from pytrip98)
Requirement already up-to-date: pydicom in /usr/local/lib/python2.7/dist-packages (from pytrip98)
Requirement already up-to-date: cycler in /usr/local/lib/python2.7/dist-packages (from matplotlib->pytrip98)
Requirement already up-to-date: pyparsing!=2.0.0,!=2.0.4,!=2.1.2,>=1.5.6 in /usr/local/lib/python2.7/dist-packages (from matplotlib->pytrip98)
Requirement already up-to-date: pytz in /usr/local/lib/python2.7/dist-packages (from matplotlib->pytrip98)
Requirement already up-to-date: python-dateutil in /usr/local/lib/python2.7/dist-packages (from matplotlib->pytrip98)
Requirement already up-to-date: six in /usr/lib/python2.7/dist-packages (from cycler->matplotlib->pytrip98)
Installing collected packages: numpy, scipy
  Found existing installation: numpy 1.11.1rc1
    Not uninstalling numpy at /usr/lib/python2.7/dist-packages, outside environment /usr
  Found existing installation: scipy 0.18.0
    Uninstalling scipy-0.18.0:
      Successfully uninstalled scipy-0.18.0
Successfully installed numpy-1.11.1 scipy-0.18.1
root@baslup:/home/bassler# pip install pytripgui
Collecting pytripgui
  Could not find a version that satisfies the requirement pytripgui (from versions: )
No matching distribution found for pytripgui
```

**Comment by grzanka** [comment]
Read carefully instructions here: https://github.com/pytrip/pytripgui

The command to install is (as described on github):

```pip install pytrip98gui```

and not:

```pip install pytripgui```

**Comment by grzanka** [comment]
The reason is that pytrip name is already taken in pip repository (see https://pypi.python.org/pypi/PYTRip)
thus I named the core library pip package as pytrip98 and GUI as pytrip98gui.

**Comment by grzanka** [comment]
I can rename GUI pip package to pytripgui, but then we would have: pytrip98 as core library and pytripgui (without 98) as GUI

**Comment by nbassler** [comment]
Naah, better be consistent with the package names. pytrip98gui is good enough I guess.

**Comment by nbassler** [comment]
However:

```
bassler@baslup:~$ pytripgui 
Traceback (most recent call last):
  File "/usr/local/bin/pytripgui", line 7, in <module>
    from pytripgui.main import start
  File "/usr/local/lib/python2.7/dist-packages/pytripgui/__init__.py", line 19, in <module>
    from pytripgui.main import start, MainFrame
  File "/usr/local/lib/python2.7/dist-packages/pytripgui/main.py", line 23, in <module>
    import wx, wx.lib.dialogs
ImportError: No module named wx
```

**Comment by grzanka** [comment]
Installation instruction not ready yet, but you can follow this one:
https://github.com/pytrip/pytripgui/blob/master/install_deps.sh

**Comment by nbassler** [comment]
On debian testing python-wxgtk3.0 was needed (2.7 does not exist there).

Works then. Guess this one can be closed when installation manual is updated?

**Comment by grzanka** [comment]
Could you make two new issues:
 - make installation instruction
 - solve the issue with python-wxgtk3.0
and close this one ?

**Comment by nbassler** [comment]
There is no issue with python-wxgtk3.0, it works out of the box.

Will make an issue to update the installer notes
