### ISSUE TITLE
Check if dependency on python-tk can be avoideded

### ISSUE THREAD

**Issue by nbassler** [pytrip/pytripgui#22]
It seems strange that python-tk is needed. 

Apparently due to matplotlib, but perhaps it can be avoided?

```
bassler@baslup:~$ pytripgui 
/usr/local/lib/python2.7/dist-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
Traceback (most recent call last):
  File "/usr/local/bin/pytripgui", line 7, in <module>
    from pytripgui.main import start
  File "/usr/local/lib/python2.7/dist-packages/pytripgui/__init__.py", line 19, in <module>
    from pytripgui.main import start, MainFrame
  File "/usr/local/lib/python2.7/dist-packages/pytripgui/main.py", line 31, in <module>
    from pytripgui.panels.plotpanel import *
  File "/usr/local/lib/python2.7/dist-packages/pytripgui/panels/__init__.py", line 19, in <module>
    import plotpanel
  File "/usr/local/lib/python2.7/dist-packages/pytripgui/panels/plotpanel.py", line 37, in <module>
    import matplotlib.pyplot as plt
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 114, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_tkagg.py", line 6, in <module>
    from matplotlib.externals.six.moves import tkinter as Tk
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/externals/six.py", line 199, in load_module
    mod = mod._resolve()
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/externals/six.py", line 113, in _resolve
    return _import_module(self.mod)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/externals/six.py", line 80, in _import_module
    __import__(name)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 42, in <module>
    raise ImportError, str(msg) + ', please install the python-tk package'
ImportError: No module named _tkinter, please install the python-tk package
```

**Comment by nbassler** [comment]
not sure if this still applies
