### ISSUE TITLE
Adding and executing second plan makes app crashing

### ISSUE THREAD

**Issue by grzanka** [pytrip/pytripgui#233]
```
TRiP98> exitTRiP98> * second.exec created by PyTRiP98 on the 2019-09-03 13:42:42.015802
TRiP98> *
TRiP98> time / on
TRiP98> sis  * /delete
<E> trpsis.c(BaseDelete) *: no such projectile
<E> trpcmdsis.c: no such projectile
TRiP98> hlut * /delete
TRiP98> ddd  * /delete
<E> trpddd.c(PrimDelete): no such projectile
<E> trpcmdddd.c: no such projectile
TRiP98> dedx * /delete
<E> *: no such material
<E> trpcmddedx.c: no such material
TRiP98> dedx "/home/grzanka/usr/trip98/trip98_1310/DATA/DEDX/20000830.dedx" / read
TRiP98> hlut "/home/grzanka/usr/trip98/trip98_1310/DATA/HLUT/19990218.hlut" / read
TRiP98> ddd "/home/grzanka/usr/trip98/trip98_1310/DATA/DDD/12C/RF3MM/*" / read
TRiP98> spc "/home/grzanka/usr/trip98/trip98_1310/DATA/SPC/12C/RF3MM/*" / read
TRiP98> sis "/home/grzanka/usr/trip98/trip98_1310/DATA/SIS/19981218.sis" / read
TRiP98> scancap / offh2o(0.000) rifi(0.000) bolus(0.000) minparticles(5000) path(none)
TRiP98> random 1000
TRiP98> ct "second" / read
1999 -29
<E> trpcube.c(Read): read hed file failed
<E> trpct.c(Read): cube read failed
<E> trpct.c(4DRead): cube read failed
<E> trpcmdct.c: cube read failed
TRiP98> voi "second" / read select("BODY_P")
<E> trpvoi.c(BaseReadBinary): VOI read: file not found
<E> trpvoi.c(BaseIsValid): no volumes defined (empty base)
<E> trpvoi.c(BaseMerge): no volumes defined (empty base)
<E> trpcmdvoi.c: no volumes defined (empty base)
TRiP98> voi "BODY_P" / maxdosefraction(1.000)
<E> trpvoi.c(BaseIsValid): no volumes defined (empty base)
<E> trpvoi.c(BaseMaxDoseFraction): no volumes defined (empty base)
<E> trpcmdvoi.c: no volumes defined (empty base)
TRiP98> field 1 / new fwhm(4.000) raster(2.00,2.00) couch(0.0) gantry(90.0) doseext(1.2000) contourext(0.60) zsteps(1.000) proj(C)
<E> trpcmdfld.c: no CT available
TRiP98> plan / dose(2.00) 
TRiP98> opt / field(*) H2Obased phys dosealg(cl) optalg(cg) geps(1.00e-04) eps(1.00e-03) iter(500)
<E> trpfld.c(BaseRefCopyFromStr): empty field list
<E> *: bad field list
TRiP98> dose "second." /calculate  alg(cl) field(*) write
<E> trpfld.c(BaseRefCopyFromStr): empty field list
<E> *: bad field
TRiP98> exit
Traceback (most recent call last):
  File "/home/grzanka/PycharmProjects/pytripgui/pytripgui/controller/tree_menu_cont.py", line 142, in execute_plan
    te.execute(plan)
  File "/home/grzanka/PycharmProjects/pytrip/pytrip/tripexecuter/execute.py", line 141, in execute
    self._finish(plan)
  File "/home/grzanka/PycharmProjects/pytrip/pytrip/tripexecuter/execute.py", line 394, in _finish
    shutil.copy(_path, plan._working_dir)
  File "/home/grzanka/anaconda3/envs/pytripgui/lib/python3.6/shutil.py", line 245, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/grzanka/anaconda3/envs/pytripgui/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/home/grzanka/tmp/exerc/trip98_wqmm8kp6/second.phys.dos'
[1]    13877 abort (core dumped)  PYTHONPATH=.:../pytrip python pytripgui/main.py
```

![image](https://user-images.githubusercontent.com/7374733/64170667-f7b43a00-ce50-11e9-8ba0-a53c7193b5d9.png)

**Comment by rozchlastywacz** [comment]
![image](https://user-images.githubusercontent.com/44035398/124356247-4aa9d480-dc15-11eb-8009-c3cdb197072b.png)
![image](https://user-images.githubusercontent.com/44035398/124356249-4bdb0180-dc15-11eb-8454-f2b8c7ca005e.png)

made 2 separete plans, both worked correctly
