### ISSUE TITLE
Problem with installation from pip

### ISSUE THREAD

**Issue by grzanka** [pytrip/pytripgui#248]
```
(pytrip516) grzanka@grzanka-VirtualBox:~/tmp$ pip install pytrip98gui
Collecting pytrip98gui
  Downloading pytrip98gui-0.3.2.tar.gz (134 kB)
     |████████████████████████████████| 134 kB 1.0 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /home/grzanka/.conda/envs/pytrip516/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-f2ufvxo3/pytrip98gui/setup.py'"'"'; __file__='"'"'/tmp/pip-install-f2ufvxo3/pytrip98gui/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-f2ufvxo3/pytrip98gui/pip-egg-info
         cwd: /tmp/pip-install-f2ufvxo3/pytrip98gui/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-f2ufvxo3/pytrip98gui/setup.py", line 116, in <module>
        version=get_version(),
      File "/tmp/pip-install-f2ufvxo3/pytrip98gui/setup.py", line 94, in get_version
        if '*@' in parsed_version[1]:
    TypeError: 'Version' object does not support indexing
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by grzanka** [comment]
I was trying to install a very old source package on python 3.6, it doesn't make sense.
