### ISSUE TITLE
Installation from github master via pip - problems

### ISSUE THREAD

**Issue by grzanka** [pytrip/pytripgui#249]
It seems that when installation from github is used, pyqt5 is not automatically fetched:

```
pytrip516) grzanka@grzanka-VirtualBox:~/tmp$ pip install git+https://github.com/pytrip/pytripgui.git
Collecting git+https://github.com/pytrip/pytripgui.git
  Cloning https://github.com/pytrip/pytripgui.git to /tmp/pip-req-build-j47bc07l
  Running command git clone -q https://github.com/pytrip/pytripgui.git /tmp/pip-req-build-j47bc07l
Requirement already satisfied: numpy in /home/grzanka/.conda/envs/pytrip516/lib/python3.6/site-packages (from pytrip98gui==0.4.0) (1.17.5)
Collecting scipy
  Downloading scipy-1.4.1-cp36-cp36m-manylinux1_x86_64.whl (26.1 MB)
     |████████████████████████████████| 26.1 MB 35.5 MB/s 
Requirement already satisfied: pytrip98 in /home/grzanka/.conda/envs/pytrip516/lib/python3.6/site-packages (from pytrip98gui==0.4.0) (2.5.6+rev4)
Requirement already satisfied: pydicom in /home/grzanka/.conda/envs/pytrip516/lib/python3.6/site-packages (from pytrip98->pytrip98gui==0.4.0) (1.4.1)
Requirement already satisfied: matplotlib in /home/grzanka/.conda/envs/pytrip516/lib/python3.6/site-packages (from pytrip98->pytrip98gui==0.4.0) (3.1.3)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/grzanka/.conda/envs/pytrip516/lib/python3.6/site-packages (from matplotlib->pytrip98->pytrip98gui==0.4.0) (1.1.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /home/grzanka/.conda/envs/pytrip516/lib/python3.6/site-packages (from matplotlib->pytrip98->pytrip98gui==0.4.0) (2.4.6)
Requirement already satisfied: python-dateutil>=2.1 in /home/grzanka/.conda/envs/pytrip516/lib/python3.6/site-packages (from matplotlib->pytrip98->pytrip98gui==0.4.0) (2.8.1)
Requirement already satisfied: cycler>=0.10 in /home/grzanka/.conda/envs/pytrip516/lib/python3.6/site-packages (from matplotlib->pytrip98->pytrip98gui==0.4.0) (0.10.0)
Requirement already satisfied: setuptools in /home/grzanka/.conda/envs/pytrip516/lib/python3.6/site-packages (from kiwisolver>=1.0.1->matplotlib->pytrip98->pytrip98gui==0.4.0) (45.1.0.post20200127)
Requirement already satisfied: six>=1.5 in /home/grzanka/.conda/envs/pytrip516/lib/python3.6/site-packages (from python-dateutil>=2.1->matplotlib->pytrip98->pytrip98gui==0.4.0) (1.14.0)
Building wheels for collected packages: pytrip98gui
  Building wheel for pytrip98gui (setup.py) ... done
  Created wheel for pytrip98gui: filename=pytrip98gui-0.4.0-py3-none-any.whl size=51217 sha256=76003fdd4e27fdb3ad4133de1f4ae8c7e982629b7781e5a51f883154056daa68
  Stored in directory: /tmp/pip-ephem-wheel-cache-mzn4kq3c/wheels/10/b6/77/5ac081373672b816904a2ed182b96e70b0ae5f6730b7be9cc5
Successfully built pytrip98gui
Installing collected packages: scipy, pytrip98gui
Successfully installed pytrip98gui-0.4.0 scipy-1.4.1
(pytrip516) grzanka@grzanka-VirtualBox:~/tmp$ pytripgui 
fatal: not a git repository (or any of the parent directories): .git
Traceback (most recent call last):
  File "/home/grzanka/.conda/envs/pytrip516/bin/pytripgui", line 5, in <module>
    from pytripgui.main import start
  File "/home/grzanka/.conda/envs/pytrip516/lib/python3.6/site-packages/pytripgui/main.py", line 5, in <module>
    from PyQt5.QtWidgets import QApplication
ModuleNotFoundError: No module named 'PyQt5'

```

**Comment by grzanka** [comment]
Moreover another error message appears once pyqt5 is installed:
```
(pytrip516) grzanka@grzanka-VirtualBox:~/tmp$ pytripgui 
fatal: not a git repository (or any of the parent directories): .git
Traceback (most recent call last):
  File "/home/grzanka/.conda/envs/pytrip516/bin/pytripgui", line 5, in <module>
    from pytripgui.main import start
  File "/home/grzanka/.conda/envs/pytrip516/lib/python3.6/site-packages/pytripgui/main.py", line 7, in <module>
    from pytripgui.main_window_qt_vc.main_window_view import MainWindowQtView
ModuleNotFoundError: No module named 'pytripgui.main_window_qt_vc'
```
