### ISSUE TITLE
Proton plan fails with TRiP98 error

### ISSUE THREAD

**Issue by grzanka** [pytrip/pytripgui#268]
An example plan dump:
```
(pytripgui_259) grzanka@grzanka-VirtualBox:~$ pytripgui 
TRiP98> exitTRiP98> * inspire.exec created by PyTRiP98 on the 2020-02-06 19:26:02.573726
TRiP98> *
TRiP98> time / on
TRiP98> sis  * /delete
<E> trpsis.c(BaseDelete) *: no such projectile
<E> trpcmdsis.c: no such projectile
TRiP98> hlut * /delete
TRiP98> ddd  * /delete
<E> trpddd.c(PrimDelete): no such projectile
<E> trpcmdddd.c: no such projectile
TRiP98> dedx * /delete
<E> *: no such material
<E> trpcmddedx.c: no such material
TRiP98> dedx "/home/grzanka/workspace/trip98_1310/DATA/DEDX/19990517.dedx" / read
TRiP98> hlut "/home/grzanka/workspace/trip98_1310/DATA/19990211.hlut" / read
TRiP98> ddd "/home/grzanka/workspace/data_ddd/*" / read
TRiP98> sis "/home/grzanka/workspace/1H.sis" / read
TRiP98> scancap / offh2o(0.000) rifi(0.000) bolus(0.000) minparticles(5000) path(none)
TRiP98> random 1000
TRiP98> ct "inspire" / read
TRiP98> voi "inspire" / read select("External")
TRiP98> voi "External" / maxdosefraction(1.000)
TRiP98> field 1 / new fwhm(4.000) raster(2.00,2.00) couch(0.0) gantry(0.0) doseext(1.2000) contourext(0.60) zsteps(1.000) proj(H)
<E> -204: raster position outside scanner limits
<E> trpcmdfld.c: setup of raster failed
TRiP98> plan / dose(2.00) 
TRiP98> opt / field(*) H2Obased phys dosealg(cl) optalg(cg) geps(1.00e-04) eps(1.00e-03) iter(500)
<E> trpfld.c(BaseRefCopyFromStr): empty field list
<E> *: bad field list
TRiP98> dose "inspire." /calculate  alg(cl) field(*) write
<E> trpfld.c(BaseRefCopyFromStr): empty field list
<E> *: bad field
TRiP98> exit
Traceback (most recent call last):
  File "/home/grzanka/.conda/envs/pytripgui_259/lib/python3.6/site-packages/pytripgui/treewidget_vc/treewidget_context_menu.py", line 55, in _execute_plan_callback
    self.execute_plan_callback(self._clicked_patient, self._clicked_item)
  File "/home/grzanka/.conda/envs/pytripgui_259/lib/python3.6/site-packages/pytripgui/main_window_qt_vc/main_window_cont.py", line 171, in on_execute_plan
    results = self.model.executor.execute(patient, plan)
  File "/home/grzanka/.conda/envs/pytripgui_259/lib/python3.6/site-packages/pytripgui/plan_executor/executor.py", line 40, in execute
    te.execute(plan)
  File "/home/grzanka/.conda/envs/pytripgui_259/lib/python3.6/site-packages/pytrip/tripexecuter/execute.py", line 141, in execute
    self._finish(plan)
  File "/home/grzanka/.conda/envs/pytripgui_259/lib/python3.6/site-packages/pytrip/tripexecuter/execute.py", line 394, in _finish
    shutil.copy(_path, plan._working_dir)
  File "/home/grzanka/.conda/envs/pytripgui_259/lib/python3.6/shutil.py", line 245, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/grzanka/.conda/envs/pytripgui_259/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/home/grzanka/PycharmProjects/pytripgui/tmp/trip98_2_n1hfey/inspire.phys.dos'
Aborted (core dumped)

```

**Comment by nbassler** [comment]
Bad SIS table.

**Comment by grzanka** [comment]
Previously a working plan had projectile `1H` instead of `H`:
```
ct "inspire" / read
voi "inspire" / read select("CTV2_d200mm_5cm3")
voi "CTV2_d200mm_5cm3" / maxdosefraction(1.000)
field 1 / new fwhm(4.000) raster(2.00,2.00) couch(0.0) gantry(0.0) doseext(1.2000) contourext(0.60) zsteps(1.000) proj(1H)
plan / dose(2.00) 
opt / field(*) H2Obased phys dosealg(cl) optalg(cg) geps(1.00e-04) eps(1.00e-03) iter(500)
dose "inspire." /calculate  alg(cl) field(*) write
```

**Comment by grzanka** [comment]
SIS table looks like this:
```
(pytripgui_259) grzanka@grzanka-VirtualBox:~$ cat workspace/1H.sis 
sisfile 19970801
sistable 19981218
projectile H
charge 1
mass 1
energy 0.00 focus 0.0 0.0 0.0 0.0 0.0 0.0 0.0 intensity 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
energy 88.83 focus 8.7 8.6 8.6 8.6 8.7 8.7 8.8 intensity 2E+08 1.5E+08 1E+08 8E+07 6E+07 4E+07 3E+07 2E+07 1.5E+07 1E+07 8E+06 6E+06 4E+06 3E+06 2E+06
(...)
```

**Comment by grzanka** [comment]
I will check it with raw plan exec files and TRiP98 binary

**Comment by nbassler** [comment]
Try with makesis?

**Comment by nbassler** [comment]
Wait, sorry, scancap, I think.. SIS is only the energy and focus steps...

**Comment by nbassler** [comment]
http://bio.gsi.de/DOCS/TRiP98/PRO/DOCS/trip98cmdscc.html

you may have to increase xmax and ymax, depending on your target size. Default is only +/- 9 cm.

**Comment by grzanka** [comment]
> http://bio.gsi.de/DOCS/TRiP98/PRO/DOCS/trip98cmdscc.html
> 
> you may have to increase xmax and ymax, depending on your target size. Default is only +/- 9 cm.

you are right, it is going better now:
```
TRiP98> (pytripgui_259) grzanka@grzanka-VirtualBox:~/tmp/buf$ ~/workspace/trip98_1310/bin/TRiP98 < H.exec 
--- This is TRiP98-64, Version 1310(compiled May 27 2014 19:45:59), (C) M.Kraemer@gsi.de ---
    @ grzanka-VirtualBox(Linux #31-Ubuntu SMP Fri Jan 17 17:27:26 UTC 2020 5.3.0-29-generic).
TRiP98> time / on
CPUtime used since last command     0.002 secs     0.002 secs
TRiP98> sis  * /delete
<E> trpsis.c(BaseDelete) *: no such projectile
<E> trpcmdsis.c: no such projectile
CPUtime used since last command         0 secs     0.002 secs
TRiP98> hlut * /delete
CPUtime used since last command         0 secs     0.002 secs
TRiP98> ddd  * /delete
<E> trpddd.c(PrimDelete): no such projectile
<E> trpcmdddd.c: no such projectile
CPUtime used since last command         0 secs     0.002 secs
TRiP98> dedx * /delete
<E> *: no such material
<E> trpcmddedx.c: no such material
CPUtime used since last command         0 secs     0.002 secs
TRiP98> dedx "/home/grzanka/workspace/trip98_1310/DATA/DEDX/19990517.dedx" / read
CPUtime used since last command     0.006 secs     0.008 secs
TRiP98> hlut "/home/grzanka/workspace/trip98_1310/DATA/19990211.hlut" / read
CPUtime used since last command         0 secs     0.008 secs
TRiP98> ddd "/home/grzanka/workspace/data_ddd/*" / read
CPUtime used since last command     0.064 secs     0.072 secs
TRiP98> sis "/home/grzanka/workspace/1H.sis" / read
CPUtime used since last command     0.008 secs      0.08 secs
TRiP98> scancap / offh2o(0.000) rifi(0.000) bolus(0.000) minparticles(5000) path(none) xmax(900) ymax(900)
<I> Entrance windows et al = 0 mm H2O
<I> Bolus = 0 mm H2O
<I> Stepsizes min = 1,1; max = 5,5 mm
<I> Particles min = 5000; max = 1.79769E+308
<I> Scanner Limits: x=(-900,900); y=(-900,900) mm
<I> focus to stepsize factor = 0.333333
<I> maxjump: dx=5 dy=5
<I> couch angles = -180 0; gantry angle = 0
<I> scanner magnet distance x = 0 mm
<I> scanner magnet distance y = 0 mm
<I> Maxim # beam    = 64
<I> Maxim # scanpos = 524288
<I> Minim # scanpos = 2
<I> Total # scanpos = 524288
<I> scanner path algorithm: none
<I> RiFi:      0.000
CPUtime used since last command         0 secs      0.08 secs
TRiP98> random 1000
CPUtime used since last command         0 secs      0.08 secs
TRiP98> ct "inspire" / read
CPUtime used since last command     0.001 secs     0.081 secs
TRiP98> voi "inspire" / read select("External")
CPUtime used since last command     0.082 secs     0.163 secs
TRiP98> voi "External" / maxdosefraction(1.000)
CPUtime used since last command         0 secs     0.163 secs
TRiP98> field 1 / new fwhm(4.000) raster(2.00,2.00) couch(0.0) gantry(0.0) doseext(1.2000) contourext(0.60) zsteps(1.000) proj(H)
<I> isocentre = 255.5 255.5 254.502
<E> trpddd.c(BaseEOfPeak): energy out of range
<E> trpfld.c(Setup): peak position from energy failed
<E> trpcmdfld.c: field setup failed
CPUtime used since last command        40 secs      40.2 secs
TRiP98> plan / dose(2.00) 
CPUtime used since last command         0 secs      40.2 secs
TRiP98> opt / field(*) H2Obased phys dosealg(cl) optalg(cg) geps(1.00e-04) eps(1.00e-03) iter(500)
<E> trpfld.c(BaseRefCopyFromStr): empty field list
<E> *: bad field list
CPUtime used since last command         0 secs      40.2 secs
TRiP98> dose "inspire." /calculate  alg(cl) field(*) write
<E> trpfld.c(BaseRefCopyFromStr): empty field list
<E> *: bad field
CPUtime used since last command         0 secs      40.2 secs
```

**Comment by nbassler** [comment]
Next one could be SIS or .ddd files covering to small interval.

That said, we need better ways of how PyTRiP handles TRiP exiting with error, without crashing pytrip.

**Comment by grzanka** [comment]
Got it, wrong target selected (full water tank). With a correct one it works like charm:

```
(pytripgui_259) grzanka@grzanka-VirtualBox:~/tmp/buf$ ~/workspace/trip98_1310/bin/TRiP98 < H.exec 
--- This is TRiP98-64, Version 1310(compiled May 27 2014 19:45:59), (C) M.Kraemer@gsi.de ---
    @ grzanka-VirtualBox(Linux #31-Ubuntu SMP Fri Jan 17 17:27:26 UTC 2020 5.3.0-29-generic).
TRiP98> time / on
CPUtime used since last command     0.002 secs     0.002 secs
TRiP98> sis  * /delete
<E> trpsis.c(BaseDelete) *: no such projectile
<E> trpcmdsis.c: no such projectile
CPUtime used since last command         0 secs     0.002 secs
TRiP98> hlut * /delete
CPUtime used since last command         0 secs     0.002 secs
TRiP98> ddd  * /delete
<E> trpddd.c(PrimDelete): no such projectile
<E> trpcmdddd.c: no such projectile
CPUtime used since last command         0 secs     0.002 secs
TRiP98> dedx * /delete
<E> *: no such material
<E> trpcmddedx.c: no such material
CPUtime used since last command         0 secs     0.002 secs
TRiP98> dedx "/home/grzanka/workspace/trip98_1310/DATA/DEDX/19990517.dedx" / read
CPUtime used since last command     0.006 secs     0.008 secs
TRiP98> hlut "/home/grzanka/workspace/trip98_1310/DATA/19990211.hlut" / read
CPUtime used since last command         0 secs     0.008 secs
TRiP98> ddd "/home/grzanka/workspace/data_ddd/*" / read
CPUtime used since last command     0.068 secs     0.076 secs
TRiP98> sis "/home/grzanka/workspace/1H.sis" / read
CPUtime used since last command     0.008 secs     0.084 secs
TRiP98> scancap / offh2o(0.000) rifi(0.000) bolus(0.000) minparticles(5000) path(none) xmax(900) ymax(900)
<I> Entrance windows et al = 0 mm H2O
<I> Bolus = 0 mm H2O
<I> Stepsizes min = 1,1; max = 5,5 mm
<I> Particles min = 5000; max = 1.79769E+308
<I> Scanner Limits: x=(-900,900); y=(-900,900) mm
<I> focus to stepsize factor = 0.333333
<I> maxjump: dx=5 dy=5
<I> couch angles = -180 0; gantry angle = 0
<I> scanner magnet distance x = 0 mm
<I> scanner magnet distance y = 0 mm
<I> Maxim # beam    = 64
<I> Maxim # scanpos = 524288
<I> Minim # scanpos = 2
<I> Total # scanpos = 524288
<I> scanner path algorithm: none
<I> RiFi:      0.000
CPUtime used since last command         0 secs     0.084 secs
TRiP98> random 1000
CPUtime used since last command         0 secs     0.084 secs
TRiP98> ct "inspire" / read
CPUtime used since last command     0.001 secs     0.085 secs
TRiP98> voi "inspire" / read select("CTV2_d200mm_5cm3")
CPUtime used since last command     0.083 secs     0.168 secs
TRiP98> voi "CTV2_d200mm_5cm3" / maxdosefraction(1.000)
CPUtime used since last command         0 secs     0.168 secs
TRiP98> field 1 / new fwhm(4.000) raster(2.00,2.00) couch(0.0) gantry(0.0) doseext(1.2000) contourext(0.60) zsteps(1.000) proj(H)
<I> isocentre = 255.5 255.5 254.5
CPUtime used since last command     0.543 secs     0.711 secs
TRiP98> plan / dose(2.00) 
CPUtime used since last command         0 secs     0.711 secs
TRiP98> opt / field(*) H2Obased phys dosealg(cl) optalg(cg) geps(1.00e-04) eps(1.00e-03) iter(500)
<D> partial dose=2
<D> absorbed dose, field 1/1...
<I> Match: average # iterations: 5 0.0344006
<I> H2OCG: average # iterations: 2.75442 0.0563642
<I>        average   myFac     : 1
<D> pre-optimization=0 sec.s
CPUtime used since last command     0.203 secs     0.914 secs
TRiP98> dose "inspire." /calculate  alg(cl) field(*) write
<I> slice=1/510 0.5
```

**Comment by nbassler** [comment]
nice!

**Comment by grzanka** [comment]
> That said, we need better ways of how PyTRiP handles TRiP exiting with error, without crashing pytrip.

I fully agree with that. It is also crashing GUI completely.
