### ISSUE TITLE
Plan -> New plan doesn't work

### ISSUE THREAD

**Issue by grzanka** [pytrip/pytripgui#279]
I've just started app without loading any patient data, clicked on Plan -> New plan. 
App is crashing with:
```
(pytripgui_ljelen_tmp) grzanka@grzanka-VirtualBox:~/PycharmProjects/pytripgui$ PYTHONPATH=. python pytripgui/main.py 
Traceback (most recent call last):
  File "/home/grzanka/PycharmProjects/pytripgui/pytripgui/main_window_qt_vc/main_window_cont.py", line 103, in on_add_new_plan
    if not patient.ctx or not patient.vdx:
AttributeError: 'bool' object has no attribute 'ctx'
Aborted (core dumped)
```
![image](https://user-images.githubusercontent.com/7374733/81929203-e67a1a80-95e6-11ea-9728-50525fceb939.png)

I suggest to disable this menu item when no patient is loaded

**Comment by grzanka** [comment]
I've loaded plan with File -> Open Voxelplan and clicked on menu item Plan -> New plan. 
App is crashing in same way

![image](https://user-images.githubusercontent.com/7374733/81929597-95b6f180-95e7-11ea-8837-9b77a4fd7db5.png)

```
(pytripgui_ljelen_tmp) grzanka@grzanka-VirtualBox:~/PycharmProjects/pytripgui$ PYTHONPATH=. python pytripgui/main.py 
Traceback (most recent call last):
  File "/home/grzanka/PycharmProjects/pytripgui/pytripgui/main_window_qt_vc/main_window_cont.py", line 103, in on_add_new_plan
    if not patient.ctx or not patient.vdx:
AttributeError: 'bool' object has no attribute 'ctx'
Aborted (core dumped)
```
