### ISSUE TITLE
Problem opening several dialogs on debian testing using wx3.0

### ISSUE THREAD

**Issue by nbassler** [pytrip/pytripgui#30]
E.g. open voxelplan
```
Traceback (most recent call last):
  File "/home/bassler/Projects/pytripgui/pytripgui/main.py", line 316, in voxelplan_load_dialog
    message="Choose headerfile")
  File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/_windows.py", line 3139, in __init__
    _windows_.FileDialog_swiginit(self,_windows_.new_FileDialog(*args, **kwargs))
PyAssertionError: C++ assertion "Assert failure" failed at ../src/common/filefn.cpp(1685) in wxParseCommonDialogsFilter(): missing '|' in the wildcard string!

```

**Comment by grzanka** [comment]
Probably replacing:

```wildcard="TRiP Exec File (*.exec)|*.exec|"```

with 

```wildcard="TRiP Exec File (*.exec)|*.exec"```

might help

**Comment by grzanka** [comment]
See similar problem here https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=772721
