### ISSUE TITLE
Cannot edit plans

### ISSUE THREAD

**Issue by nbassler** [pytrip/pytripgui#33]
Accessing properties  of plan or structures results in

```
Traceback (most recent call last):
  File "/home/bassler/.local/lib/python2.7/site-packages/pytripgui/leftmenu.py", line 210, in plan_properties_field
    pub.sendMessage("gui.field.open", field)
  File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/lib/pubsub/core/arg1/publisher.py", line 36, in sendMessage
    topicObj.publish(data)
  File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/lib/pubsub/core/arg1/publishermixin.py", line 23, in publish
    self._publish(data)
  File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/lib/pubsub/core/topicobj.py", line 383, in _publish
    self.__sendMessage(data, topicObj, iterState)
  File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/lib/pubsub/core/topicobj.py", line 397, in __sendMessage
    self._mix_callListener(listener, data, iterState)
  File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/lib/pubsub/core/arg1/publishermixin.py", line 34, in _mix_callListener
    listener(self, data)
  File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/lib/pubsub/core/arg1/listenerimpl.py", line 51, in __call__
    cb(msg, **kwargs)
  File "/home/bassler/.local/lib/python2.7/site-packages/pytripgui/main.py", line 116, in load_dialog
    pytripDialog.Init(msg.data)
  File "/home/bassler/.local/lib/python2.7/site-packages/pytripgui/dialogs/fielddialog.py", line 41, in Init
    self.check_isocenter.Bind(wx.EVT_CHECKBOX, self.on_check_isocenter_changed)
AttributeError: 'NoneType' object has no attribute 'Bind'
```

**Comment by grzanka** [comment]
@nbassler can you check again ?

**Comment by nbassler** [comment]
PyTRiP 1.3.1
PyTRiPGUI 0.2.1
See screenshot
![screenshot_2017-02-10_14-40-46](https://cloud.githubusercontent.com/assets/7140398/22828706/1ee4e612-ef9f-11e6-950a-579302b90f29.png)

Open plan TST000 -> New Plan -> some structure open the "Properties" dialog
