### ISSUE TITLE
changing color scale for HUs results in error

### ISSUE THREAD

**Issue by nbassler** [pytrip/pytripgui#34]
... when going to extreme limits

```
Traceback (most recent call last):
  File "/home/bassler/.local/lib/python2.7/site-packages/matplotlib/backends/backend_wx.py", line 1154, in _onMotion
    FigureCanvasBase.motion_notify_event(self, x, y, guiEvent=evt)
  File "/home/bassler/.local/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 1952, in motion_notify_event
    self.callbacks.process(s, event)
  File "/home/bassler/.local/lib/python2.7/site-packages/matplotlib/cbook.py", line 563, in process
    proxy(*args, **kwargs)
  File "/home/bassler/.local/lib/python2.7/site-packages/matplotlib/cbook.py", line 430, in __call__
    return mtd(*args, **kwargs)
  File "/home/bassler/.local/lib/python2.7/site-packages/pytripgui/panels/plotpanel.py", line 330, in on_mouse_move_plot
    self.Draw()
  File "/home/bassler/.local/lib/python2.7/site-packages/pytripgui/panels/plotpanel.py", line 639, in Draw
    self.plotutil.plot(self.image_idx)
  File "/home/bassler/.local/lib/python2.7/site-packages/pytripgui/guiutil.py", line 322, in plot
    self.plot_text(idx)
  File "/home/bassler/.local/lib/python2.7/site-packages/pytripgui/guiutil.py", line 519, in plot_text
    "W / L: %d / %d" % (self.contrast[1], self.contrast[0]),
TypeError: %d format: a number is required, not numpy.float64
```

**Comment by nbassler** [comment]
some bound checking is missing. Can be reproduced when going to negative values.
