### ISSUE TITLE
Can't execute plan on patient imported from dicom

### ISSUE THREAD

**Issue by ljelen** [pytrip/pytripgui#345]
The following error appears while executing plan:

```
TRiP98> voi "Patient" / read select("CTV_6000")
<E> trpvoi.c(BaseReadBinary): VOI read: file not found
<E> trpvoi.c(BaseIsValid): no volumes defined (empty base)
<E> trpvoi.c(BaseMerge): no volumes defined (empty base)
<E> trpcmdvoi.c: no volumes defined (empty base)
TRiP98> voi "CTV_6000" / maxdosefraction(1.000)
<E> trpvoi.c(BaseIsValid): no volumes defined (empty base)
<E> trpvoi.c(BaseMaxDoseFraction): no volumes defined (empty base)
<E> trpcmdvoi.c: no volumes defined (empty base)
TRiP98> field 1 / new fwhm(4.000) raster(2.00,2.00) couch(0.0) gantry(0.0) doseext(1.2000) contourext(0.60) zsteps(1.000) proj(C)
<E> trpcmdfld.c: no CT available
TRiP98> plan / dose(2.00) 
TRiP98> opt / field(*) H2Obased phys dosealg(cl) optalg(cg) geps(1.00e-04) eps(1.00e-03) iter(500)
<E> trpfld.c(BaseRefCopyFromStr): empty field list
<E> *: bad field list
TRiP98> dose "Patient." /calculate  alg(cl) field(*) write
<E> trpfld.c(BaseRefCopyFromStr): empty field list
<E> *: bad field
TRiP98> exit
Traceback (most recent call last):
  File "/home/deerjelen/dev/ifj/PycharmProjects/pytripgui/pytripgui/main_window_qt_vc/main_window_cont.py", line 70, in on_execute_selected_plan
    self.patient_tree.selected_item_patient()
  File "/home/deerjelen/dev/ifj/PycharmProjects/pytripgui/pytripgui/app_logic/app_callbacks.py", line 84, in execute_plan
    item.data = self.executor.execute(patient.data, plan.data)
  File "/home/deerjelen/dev/ifj/PycharmProjects/pytripgui/pytripgui/plan_executor/executor.py", line 35, in execute
    te.execute(plan)
  File "/home/deerjelen/app/anaconda3/envs/pytripgui/lib/python3.6/site-packages/pytrip/tripexecuter/execute.py", line 141, in execute
    self._finish(plan)
  File "/home/deerjelen/app/anaconda3/envs/pytripgui/lib/python3.6/site-packages/pytrip/tripexecuter/execute.py", line 394, in _finish
    shutil.copy(_path, plan._working_dir)
  File "/home/deerjelen/app/anaconda3/envs/pytripgui/lib/python3.6/shutil.py", line 245, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/deerjelen/app/anaconda3/envs/pytripgui/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/home/deerjelen/dev/ifj/PycharmProjects/wdir/trip98_5vkzmrkf/Patient.phys.dos'

```

**Comment by ljelen** [comment]
resolved
