### ISSUE TITLE
Error during loading patient data

### ISSUE THREAD

**Issue by ljelen** [pytrip/pytripgui#394]
```
Traceback (most recent call last):
  File "/home/deerjelen/dev/sandbox/IFJ/pytripgui/pytripgui/view/qt_gui.py", line 105, in _on_open_voxelplan_internal_callback
    self._open_voxelplan_callback()
  File "/home/deerjelen/dev/sandbox/IFJ/pytripgui/pytripgui/app_logic/app_callbacks.py", line 36, in on_open_voxelplan
    if self.open_voxelplan_callback(patient):
  File "/home/deerjelen/dev/sandbox/IFJ/pytripgui/pytripgui/app_logic/app_callbacks.py", line 195, in open_voxelplan_callback
    self.app_model.viewcanvases = ViewCanvases()
  File "/home/deerjelen/dev/sandbox/IFJ/pytripgui/pytripgui/app_logic/viewcanvas.py", line 7, in __init__
    self.viewcanvas_view = ViewCanvasView()
  File "/home/deerjelen/dev/sandbox/IFJ/pytripgui/pytripgui/viewcanvas_vc/viewcanvas_view.py", line 31, in __init__
    self.vois_tree_set_enabled(True)
  File "/home/deerjelen/dev/sandbox/IFJ/pytripgui/pytripgui/viewcanvas_vc/viewcanvas_view.py", line 142, in vois_tree_set_enabled
    self._ui.voiList_checkBox.setCheckState(QtCore.Qt.CheckState.Checked)
AttributeError: type object 'CheckState' has no attribute 'Checked'

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)
```

**Comment by grzanka** [comment]
@ljelen is it still valid ?

**Comment by ljelen** [comment]
resolved
