### ISSUE TITLE
pytripgui does not load pinnacle dicom file

### ISSUE THREAD

**Issue by Tibazz** [pytrip/pytripgui#44]
Tried to load dicom file created with pinnacle, (which includes a RTSTRUCT file in the directory as well.)

```
tibazz@trip:~/Desktop/Tibors stuff$ pytripgui 
/usr/local/lib/python2.7/dist-packages/pytripgui/main.py:365: wxPyDeprecationWarning: Call to deprecated item. 
  wx.InitAllImageHandlers()
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pytripgui/data.py", line 168, in load_from_dicom_thread
    structures.read_dicom(dicom)
  File "/usr/local/lib/python2.7/dist-packages/pytrip/vdx.py", line 96, in read_dicom
    v = Voi(dcm.RTROIObservations[i].ROIObservationLabel.decode('iso-8859-1'), self.cube)
  File "/usr/local/lib/python2.7/dist-packages/dicom/dataset.py", line 256, in __getattr__
    "'{0:s}'.".format(name))
AttributeError: Dataset does not have attribute 'ROIObservationLabel'.
```

?

**Comment by nbassler** [comment]
May be related to pytrip, and not pytripgui.
Probably this issue will be resolved with https://github.com/pytrip/pytrip/pull/224

**Comment by nbassler** [comment]
Should work with PyTRiP v. 1.3.0 (about to be released)
