### ISSUE TITLE
Cannot open patient data on Linux

### ISSUE THREAD

**Issue by grzanka** [pytrip/pytripgui#441]
When selecting file from local directory (code pulled from github) pytripgui complains and tries to open file from some weird location:

```
DEBUG:PyQt5.uic.uiparser:pop widget UiAddPatient NewPatientDialog
DEBUG:PyQt5.uic.uiparser:new topwidget None
INFO:pytrip.util:Locating : /run/user/1000/doc/21e787ae/inspire05hn.ctx as <pytrip.ctx.CtxCube object at 0x7f0063ad8f40>
INFO:pytrip.util:Found /run/user/1000/doc/21e787ae/inspire05hn.hed
INFO:pytrip.util:Locating : /run/user/1000/doc/21e787ae/inspire05hn.ctx as <pytrip.ctx.CtxCube object at 0x7f0063ad8f40>
WARNING:pytrip.util:Checking following files: /run/user/1000/doc/21e787ae/inspire05hn.ctx , /run/user/1000/doc/21e787ae/inspire05hn.CTX , /run/user/1000/doc/21e787ae/inspire05hn.ctx.gz , /run/user/1000/doc/21e787ae/inspire05hn.CTX.gz , /run/user/1000/doc/21e787ae/inspire05hn.ctx.GZ , /run/user/1000/doc/21e787ae/inspire05hn.CTX.GZ. None of them exists.
Traceback (most recent call last):
  File "/home/grzanka/PycharmProjects/pytripgui/pytripgui/view/qt_gui.py", line 103, in _on_open_voxelplan_internal_callback
    self._open_voxelplan_callback()
  File "/home/grzanka/PycharmProjects/pytripgui/pytripgui/app_logic/app_callbacks.py", line 36, in on_open_voxelplan
    if self.open_voxelplan_callback(patient):
  File "/home/grzanka/PycharmProjects/pytripgui/pytripgui/app_logic/app_callbacks.py", line 193, in open_voxelplan_callback
    patient.open_ctx(filename + ".ctx")  # Todo catch exceptions
  File "/home/grzanka/PycharmProjects/pytripgui/pytripgui/plan_executor/patient_model.py", line 19, in open_ctx
    ctx.read(path)
  File "/home/grzanka/PycharmProjects/pytripgui/venv/lib/python3.8/site-packages/pytrip/cube.py", line 430, in read
    raise FileNotFound("Loading {:s} failed, file not found".format(path))
pytrip.error.FileNotFound: 'Loading /run/user/1000/doc/21e787ae/inspire05hn.ctx failed, file not found'
```

**Comment by grzanka** [comment]
Interesting - installing it using pip is more successful:
![image](https://user-images.githubusercontent.com/7374733/130040613-ec6214f9-3bf1-4199-a6ee-1870774ca0e9.png)
![image](https://user-images.githubusercontent.com/7374733/130040919-50a9025f-ce64-418b-bdee-fa068d50ff32.png)

**Comment by grzanka** [comment]
Even more funny - starting the pytripgui from console works perfectly well.

Then problem appears only when its started from Pycharm session
