### ISSUE TITLE
Error when opening Corvus 6.2.2 Dicom CT files

### ISSUE THREAD

**Issue by grzanka** [pytrip/pytripgui#56]
Linux, pytripgui 1.2.2 + pytrip 1.3.1

Opening DICOM file from https://subversion.assembla.com/svn/slicerrt/trunk/SlicerRt/data/corvus-6.2.2-phantom/

An error:
```
→ PYTHONPATH=. python2 pytripgui/main.py                                                                                          ~/PycharmProjects/pytripgui
18:12:33: Warning: Mismatch between the program and library build versions detected.
The library used 3.0 (wchar_t,compiler with C++ ABI 1010,wx containers,compatible with 2.8),
and wxPython used 3.0 (wchar_t,compiler with C++ ABI 1009,wx containers,compatible with 2.8).
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/grzanka/PycharmProjects/pytripgui/pytripgui/data.py", line 161, in load_from_dicom_thread
    c.read_dicom(dicom)
  File "/home/grzanka/.local/lib/python2.7/site-packages/pytrip/ctx.py", line 60, in read_dicom
    self.cube[i][:][:] = data
ValueError: could not broadcast input array from shape (394,512) into shape (512,394)
```

**Comment by nbassler** [comment]
first evidence of len(x) != len(y)?

**Comment by nbassler** [comment]
Confimed, but could be PyTRiP issue

**Comment by nbassler** [comment]
https://github.com/pytrip/pytrip/issues/387
