### ISSUE TITLE
Error when opening Eclipe 8.6.15 CT files

### ISSUE THREAD

**Issue by grzanka** [pytrip/pytripgui#57]
Linux, pytripgui 1.2.2 + pytrip 1.3.1

Opening DICOM file from https://subversion.assembla.com/svn/slicerrt/trunk/SlicerRt/data/eclipse-8.6.15-phantom-brachy/

An error:
→ PYTHONPATH=. python2 pytripgui/main.py                                                                                          ~/PycharmProjects/pytripgui
18:14:56: Warning: Mismatch between the program and library build versions detected.
The library used 3.0 (wchar_t,compiler with C++ ABI 1010,wx containers,compatible with 2.8),
and wxPython used 3.0 (wchar_t,compiler with C++ ABI 1009,wx containers,compatible with 2.8).
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/grzanka/PycharmProjects/pytripgui/pytripgui/data.py", line 167, in load_from_dicom_thread
    structures = VdxCube(c)
UnboundLocalError: local variable 'c' referenced before assignment

**Comment by nbassler** [comment]
Sure you dont have conflicting pytrip python2  installations?

**Comment by nbassler** [comment]
Confirmed, 
PyTRiPGUI 0.2.2. 
PyTRiP 1.3.1

Opening DICOM file from https://subversion.assembla.com/svn/slicerrt/trunk/SlicerRt/data/eclipse-8.6.15-phantom-brachy/
```
bassler@baslup:~$ pytripgui 
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/bassler/.local/lib/python2.7/site-packages/pytripgui/data.py", line 167, in load_from_dicom_thread
    structures = VdxCube(c)
UnboundLocalError: local variable 'c' referenced before assignment
```

**Comment by nbassler** [comment]
After API upgrade #123 it persists:
![image](https://user-images.githubusercontent.com/7140398/28792667-b3d2a9ae-7630-11e7-93b7-87bb33aefd77.png)

**Comment by nbassler** [comment]
https://subversion.assembla.com/svn/slicerrt/trunk/SlicerRt/data/eclipse-8.6.15-phantom-brachy/

There are only MR data here, one may think how this should be handled. Some error message should appear, if there are no CT data.
