### ISSUE TITLE
pytripgui refuses to load .dos of .dosemeanlet cubes

### ISSUE THREAD

**Issue by nbassler** [pytrip/pytripgui#87]
bassler@baslup:~/Projects/dasu01$ Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/bassler/.local/lib/python2.7/site-packages/pytripgui/data.py", line 206, in load_from_voxelplan_thread
    raise InputError("No Images")
InputError: 'No Images'

**Comment by grzanka** [comment]
Can you share some example ?

**Comment by grzanka** [comment]
I've already improved a bit reading of TRiP98 plans, but I need a bit more details:  what were the filenames you've been trying to load, which format etc...

**Comment by nbassler** [comment]
try to load the .dos and dosemlet.dos from the test.tar.gz I sent you earlier. The CTX is missing, but it should still be possible to load them.
